#!/usr/bin/env bash
# Display files without hidden ones and remove first number and dash

for file in *
do
  if [[ "$file" != .* ]]
  then
    if [[ "$file" == *-* ]]
    then
      echo "${file#*-}"
    else
      echo "$file"
    fi
  fi
done
